# Use an official Node.js runtime as a base image
FROM node:18.20.5-bullseye-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application code to the container
COPY . .

# Expose the application port
EXPOSE 3000

# Run the server
CMD ["node", "index.js"]
